[build]
  command = "npm run build:netlify"
  publish = "dist/odd-one-out/browser"

# IMPORTANT: For HTML5 routing (useHash: false)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/student"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"